In [ ]:
#log20030401
import pandas as pd
 
# Load the data into a DataFrame
data = pandas.read_csv('log20030401.csv')
 
data.head(n=10)

In [ ]:
#grouping by IP
byIp = data.groupby('ip')
byIp

In [ ]:
byCIK = data.groupby('cik')
byCIK['size'].max()

In [ ]:
#getting requests with  status code 404
byIp404=data[data['code']==404]
byIp404
#Anamoly-request with 404 has a download size associated.

In [ ]:
byIp404=data[data['code']==404].groupby('ip')
byIp404['size'].mean()

In [ ]:
#1. Simple describe function on data
summary = data.describe()
summary
#Analysis: total number of requests on this day-  261289
#Average request per day :215
#Max file download size:5.259544e+07
#Avergae File donwload size:	1.703470e+05

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

from numpy import genfromtxt
from scipy.stats import multivariate_normal
from sklearn.metrics import f1_score

In [ ]:
def read_dataset(filePath,delimiter=','):
    return pandas.read_csv(filePath)

def feature_normalize(dataset):
    mu = np.mean(dataset,axis=0)
    sigma = np.std(dataset,axis=0)
    return (dataset - mu)/sigma

def estimateGaussian(dataset):
    mu = np.mean(dataset, axis=0)
    sigma = np.cov(dataset.T)
    return mu, sigma
    
def multivariateGaussian(dataset,mu,sigma):
    p = multivariate_normal(mean=mu, cov=sigma)
    return p.pdf(dataset)

def selectThresholdByCV(probs,gt):
    best_epsilon = 0
    best_f1 = 0
    f = 0
    stepsize = (max(probs) - min(probs)) / 1000;
    epsilons = np.arange(min(probs),max(probs),stepsize)
    for epsilon in np.nditer(epsilons):
        predictions = (probs < epsilon)
        f = f1_score(gt, predictions, average = "binary")
        if f > best_f1:
            best_f1 = f
            best_epsilon = epsilon
    return best_f1, best_epsilon

In [ ]:
tr_data = read_dataset('log20030401.csv') 
tr_data.head()

In [ ]:
n_training_samples = tr_data['size'].shape[0]
n_training_samples
n_dim = tr_data['code'].shape[1]
n_dim

In [ ]:

plt.figure()
plt.xlabel("Latency (ms)")
plt.ylabel("Throughput (mb/s)")
plt.plot(tr_data[:,0],tr_data[:,1],"bx")
plt.show()

In [ ]:
dataCIK = pandas.read_csv('CIK-mapping.csv')
 
dataCIK.head(n=10)
dataCIK.dtypes
dataCIK['CIK']
dataCIK['CIK'].astype(np.float64)

In [ ]:
mergedDf=pd.merge(dataCIK, data, left_on='CIK', right_on='cik')

In [ ]:
data.head()

In [ ]:
data.dtypes

In [ ]:
byIp=mergedDf.groupby('ip')
byIp['company'].describe()

In [ ]:
mergedDf.groupby('company').describe()

In [ ]:
rows = np.random.choice(mergedDf.index.values, 10)
sampled_df = mergedDf.ix[rows]
sampled_df

In [50]:
sampled_df.groupby('company').describe()

                                                                CIK  \
company
ALCAN INC                                          count        1.0
                                                   mean      4285.0
                                                   std          NaN
                                                   min       4285.0
                                                   25%       4285.0
                                                   50%       4285.0
                                                   75%       4285.0
                                                   max       4285.0
COLLABRX, INC.                                     count        1.0
                                                   mean    931059.0
                                                   std          NaN
                                                   min     931059.0
                                                   25%     931059.0
                                                   50%     931059.0
                                                   75%     931059.0
                                                   max     931059.0
CULLEN FROST BANKERS INC                           count        1.0
                                                   mean     39263.0
                                                   std          NaN
                                                   min      39263.0
                                                   25%      39263.0
                                                   50%      39263.0
                                                   75%      39263.0
                                                   max      39263.0
LAND O LAKES FARMLAND FEED LLC                     count        1.0
                                                   mean   1174731.0
                                                   std          NaN
                                                   min    1174731.0
                                                   25%    1174731.0
                                                   50%    1174731.0
...                                                             ...
ORTHODONTIC CENTERS OF AMERICA INC /DE/            std          NaN
                                                   min     931702.0
                                                   25%     931702.0
                                                   50%     931702.0
                                                   75%     931702.0
                                                   max     931702.0
ROYCE & ASSOCIATES INC                         ... count        1.0
                                                   mean    734269.0
                                                   std          NaN
                                                   min     734269.0
                                                   25%     734269.0
                                                   50%     734269.0
                                                   75%     734269.0
                                                   max     734269.0
SCHULER HOLDINGS INC                               count        1.0
                                                   mean   1126899.0
                                                   std          NaN
                                                   min    1126899.0
                                                   25%    1126899.0
                                                   50%    1126899.0
                                                   75%    1126899.0
                                                   max    1126899.0
UBS SERIES TRUST                                   count        1.0
                                                   mean    806591.0
                                                   std          NaN
                                                   min     806591.0
                                                   25%     806591.0
                                                   50%     806591.0
                                                   75%     806591.0
                                                   max     806591.0

                                                          Unnamed: 0  \
company
ALCAN INC                                          count         1.0
                                                   mean      19426.0
                                                   std           NaN
                                                   min       19426.0
                                                   25%       19426.0
                                                   50%       19426.0
                                                   75%       19426.0
                                                   max       19426.0
COLLABRX, INC.                                     count         1.0
                                                   mean     125918.0
                                                   std           NaN
                                                   min      125918.0
                                                   25%      125918.0
                                                   50%      125918.0
                                                   75%      125918.0
                                                   max      125918.0
CULLEN FROST BANKERS INC                           count         1.0
                                                   mean     144010.0
                                                   std           NaN
                                                   min      144010.0
                                                   25%      144010.0
                                                   50%      144010.0
                                                   75%      144010.0
                                                   max      144010.0
LAND O LAKES FARMLAND FEED LLC                     count         1.0
                                                   mean     335854.0
                                                   std           NaN
                                                   min      335854.0
                                                   25%      335854.0
                                                   50%      335854.0
...                                                              ...
ORTHODONTIC CENTERS OF AMERICA INC /DE/            std           NaN
                                                   min      438190.0
                                                   25%      438190.0
                                                   50%      438190.0
                                                   75%      438190.0
                                                   max      438190.0
ROYCE & ASSOCIATES INC                         ... count         1.0
                                                   mean     504340.0
                                                   std           NaN
                                                   min      504340.0
                                                   25%      504340.0
                                                   50%      504340.0
                                                   75%      504340.0
                                                   max      504340.0
SCHULER HOLDINGS INC                               count         1.0
                                                   mean     518240.0
                                                   std           NaN
                                                   min      518240.0
                                                   25%      518240.0
                                                   50%      518240.0
                                                   75%      518240.0
                                                   max      518240.0
UBS SERIES TRUST                                   count         1.0
                                                   mean     597569.0
                                                   std           NaN
                                                   min      597569.0
                                                   25%      597569.0
                                                   50%      597569.0
                                                   75%      597569.0
                                                   max      597569.0

                                                                cik   code  \
company
ALCAN INC                                          count        1.0    1.0
                                                   mean      4285.0  200.0
                                                   std          NaN    NaN
                                                   min       4285.0  200.0
                                                   25%       4285.0  200.0
                                                   50%       4285.0  200.0
                                                   75%       4285.0  200.0
                                                   max       4285.0  200.0
COLLABRX, INC.                                     count        1.0    1.0
                                                   mean    931059.0  304.0
                                                   std          NaN    NaN
                                                   min     931059.0  304.0
                                                   25%     931059.0  304.0
                                                   50%     931059.0  304.0
                                                   75%     931059.0  304.0
                                                   max     931059.0  304.0
CULLEN FROST BANKERS INC                           count        1.0    1.0
                                                   mean     39263.0  200.0
                                                   std          NaN    NaN
                                                   min      39263.0  200.0
                                                   25%      39263.0  200.0
                                                   50%      39263.0  200.0
                                                   75%      39263.0  200.0
                                                   max      39263.0  200.0
LAND O LAKES FARMLAND FEED LLC                     count        1.0    1.0
                                                   mean   1174731.0  200.0
                                                   std          NaN    NaN
                                                   min    1174731.0  200.0
                                                   25%    1174731.0  200.0
                                                   50%    1174731.0  200.0
...                                                             ...    ...
ORTHODONTIC CENTERS OF AMERICA INC /DE/            std          NaN    NaN
                                                   min     931702.0  304.0
                                                   25%     931702.0  304.0
                                                   50%     931702.0  304.0
                                                   75%     931702.0  304.0
                                                   max     931702.0  304.0
ROYCE & ASSOCIATES INC                         ... count        1.0    1.0
                                                   mean    734269.0  200.0
                                                   std          NaN    NaN
                                                   min     734269.0  200.0
                                                   25%     734269.0  200.0
                                                   50%     734269.0  200.0
                                                   75%     734269.0  200.0
                                                   max     734269.0  200.0
SCHULER HOLDINGS INC                               count        1.0    1.0
                                                   mean   1126899.0  200.0
                                                   std          NaN    NaN
                                                   min    1126899.0  200.0
                                                   25%    1126899.0  200.0
                                                   50%    1126899.0  200.0
                                                   75%    1126899.0  200.0
                                                   max    1126899.0  200.0
UBS SERIES TRUST                                   count        1.0    1.0
                                                   mean    806591.0  200.0
                                                   std          NaN    NaN
                                                   min     806591.0  200.0
                                                   25%     806591.0  200.0
                                                   50%     806591.0  200.0
                                                   75%     806591.0  200.0
                                                   max     806591.0  200.0

                                                          crawler  find  idx  \
company
ALCAN INC                                          count      1.0   1.0  1.0
                                                   mean       0.0   9.0  0.0
                                                   std        NaN   NaN  NaN
                                                   min        0.0   9.0  0.0
                                                   25%        0.0   9.0  0.0
                                                   50%        0.0   9.0  0.0
                                                   75%        0.0   9.0  0.0
                                                   max        0.0   9.0  0.0
COLLABRX, INC.                                     count      1.0   1.0  1.0
                                                   mean       0.0   9.0  0.0
                                                   std        NaN   NaN  NaN
                                                   min        0.0   9.0  0.0
                                                   25%        0.0   9.0  0.0
                                                   50%        0.0   9.0  0.0
                                                   75%        0.0   9.0  0.0
                                                   max        0.0   9.0  0.0
CULLEN FROST BANKERS INC                           count      1.0   1.0  1.0
                                                   mean       0.0   0.0  1.0
                                                   std        NaN   NaN  NaN
                                                   min        0.0   0.0  1.0
                                                   25%        0.0   0.0  1.0
                                                   50%        0.0   0.0  1.0
                                                   75%        0.0   0.0  1.0
                                                   max        0.0   0.0  1.0
LAND O LAKES FARMLAND FEED LLC                     count      1.0   1.0  1.0
                                                   mean       0.0   0.0  0.0
                                                   std        NaN   NaN  NaN
                                                   min        0.0   0.0  0.0
                                                   25%        0.0   0.0  0.0
                                                   50%        0.0   0.0  0.0
...                                                           ...   ...  ...
ORTHODONTIC CENTERS OF AMERICA INC /DE/            std        NaN   NaN  NaN
                                                   min        0.0   9.0  0.0
                                                   25%        0.0   9.0  0.0
                                                   50%        0.0   9.0  0.0
                                                   75%        0.0   9.0  0.0
                                                   max        0.0   9.0  0.0
ROYCE & ASSOCIATES INC                         ... count      1.0   1.0  1.0
                                                   mean       0.0   0.0  1.0
                                                   std        NaN   NaN  NaN
                                                   min        0.0   0.0  1.0
                                                   25%        0.0   0.0  1.0
                                                   50%        0.0   0.0  1.0
                                                   75%        0.0   0.0  1.0
                                                   max        0.0   0.0  1.0
SCHULER HOLDINGS INC                               count      1.0   1.0  1.0
                                                   mean       0.0   1.0  1.0
                                                   std        NaN   NaN  NaN
                                                   min        0.0   1.0  1.0
                                                   25%        0.0   1.0  1.0
                                                   50%        0.0   1.0  1.0
                                                   75%        0.0   1.0  1.0
                                                   max        0.0   1.0  1.0
UBS SERIES TRUST                                   count      1.0   1.0  1.0
                                                   mean       0.0   0.0  1.0
                                                   std        NaN   NaN  NaN
                                                   min        0.0   0.0  1.0
                                                   25%        0.0   0.0  1.0
                                                   50%        0.0   0.0  1.0
                                                   75%        0.0   0.0  1.0
                                                   max        0.0   0.0  1.0

                                                          noagent  norefer  \
company
ALCAN INC                                          count      1.0      1.0
                                                   mean       0.0      0.0
                                                   std        NaN      NaN
                                                   min        0.0      0.0
                                                   25%        0.0      0.0
                                                   50%        0.0      0.0
                                                   75%        0.0      0.0
                                                   max        0.0      0.0
COLLABRX, INC.                                     count      1.0      1.0
                                                   mean       0.0      0.0
                                                   std        NaN      NaN
                                                   min        0.0      0.0
                                                   25%        0.0      0.0
                                                   50%        0.0      0.0
                                                   75%        0.0      0.0
                                                   max        0.0      0.0
CULLEN FROST BANKERS INC                           count      1.0      1.0
                                                   mean       0.0      1.0
                                                   std        NaN      NaN
                                                   min        0.0      1.0
                                                   25%        0.0      1.0
                                                   50%        0.0      1.0
                                                   75%        0.0      1.0
                                                   max        0.0      1.0
LAND O LAKES FARMLAND FEED LLC                     count      1.0      1.0